### ISSUE TITLE
Remove Git mode

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#159]
Those that said they would use it, use the editor instead.

**Comment by iainbryson** [comment]
Do you want to hide it the use of git (inexpensive) or remove it entirely (more expensive, and would also get rid of versioning and "backdoor".

?

**Comment by dtu-compute** [comment]
I was thinking that the commits that added the Git Mode option could be reverted? I would prefer not to have unused code in the codebase.

What do you mean with versioning and backdoor?

**Comment by iainbryson** [comment]
If we remove git, we remove the feature of having old versions potentially accessible, and an alternative way to upload to the system.  But if you don't need those, removing the code entirely is the best option.  I'm not sure about reverting the commits though;  that would likely be very messy since they aren't one single isolated set.  Better to start from the current state and remove it cleanly.

**Comment by iainbryson** [comment]
Yes, that's what I mean.  With the git mode, we can push the state to a remote repository where it'll be versioned and could be reverted.  Without git mode that ability goes away.  I suppose you have a backup, but it's not quite the same thing as a push/mode change.  Maybe that capability is not really needed, which is fine too.

**Comment by dtu-compute** [comment]
Ok, great. Yes, there is local backup. So getting rid of Git is fine.
