### ISSUE TITLE
Sharelatex tab page

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#178]
Let's remove the current list on this page, and just have the following buttons:

* "Compile" button (that just downloads and compiles)
* "List compiled" button (opens a modal with `ls -o | cut -d ' ' -f4-`) of staging folder
* "Make online" button (moves files from staging to online folder and updates menu)
* "List online" button (opens a modal with `ls -o | cut -d ' ' -f4-`) of online folder

"Make online" sounds odd, right?

**Comment by dtu-compute** [comment]
Maybe parsing `ls` isn't the greatest idea, as the date format is not consistent. `stat --printf '%s\t%y\t%n\n' *` is a little bit better, but still odd and much to long. Perhaps there is a Ruby way of doing this? =)

**Comment by iainbryson** [comment]
We can do the equivalent of `ls`/`stat` with standard ruby libraries.

Also, maybe “make online” should be “Publish”.

Finally, do you want to be able to click on the “staging” enotes and view them in the PDF viewer?

**Comment by dtu-compute** [comment]
> Also, maybe “make online” should be “Publish”.

Perfect =)

> Finally, do you want to be able to click on the “staging” enotes and view them in the PDF viewer?

It would be a cool feature. If it can be added without affecting the budget too much, then yes for sure =)

**Comment by iainbryson** [comment]
Concerning:

> Let's remove the current list on this page, and just have the following buttons:
> "Compile" button (that just downloads and compiles)

I'm unclear how do you want to handle the long-running & async nature of the compile process if we go this direction.

Right now, the "convert & load new enotes" launches a conversion job.  Then the page is updated until the job is "complete".  If it fails, you can see why it failed in the job list.

If "Compile" does the same thing, then the user will not know when the job completes or even if it was successful.  Having to go to the "list staging" modal and figure it out from the timestamps seems more work than necessary since we have more information available to give to the user.

How about we take a middle road: instead of a list of jobs, we just show the most recent.  We show when it started, when it completed (if it has completed), and any errors if it failed and provide buttons view the staging enotes and to publish them?

**Comment by dtu-compute** [comment]
That is a very good idea I think. Is this what you had in mind?

![1](https://user-images.githubusercontent.com/13518486/38155425-fc4aa262-3477-11e8-93d8-164123a55b6e.jpg)

I like the one word buttons, and I have left out the "List published" as it might just makes things more confusing.
