### ISSUE TITLE
[]() links are broken

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#72]
After the podcast commit were made so podcasts would be inserted when ever typing `[podcast](http://...) links like this one `[Google](https://google.com)` are shown as broken.

**Comment by iainbryson** [comment]
Can you point me to a page showing the problem?  Do the links on podcast page work as expected, but links on other pages are busted?

**Comment by dtu-compute** [comment]
Let me get back to you with this one. I can't reproduce it in 00000, but the professor in 02323 could do it on his site.

**Comment by iainbryson** [comment]
Is this still a problem?

**Comment by dtu-compute** [comment]
Yes, here is this odd problem.

https://00000-enote.compute.dtu.dk/Agendas

but the exact same line
```
"bla-bla [frontpage](https://google.com) bla-bla"
```
at

https://00000-enote.compute.dtu.dk/Material

doesn't fail.

It only fails at Agendas it looks like.

**Comment by iainbryson** [comment]
Ah, OK.  I know what’s going on.

The agendas page has a special behavior with regard to links because it needs to take Markdown links which are the names of pages and turn them into links to the actual page urls.  But it doesn’t expect there to be “real” non-page links on the page.  If we need to support that, we’ll have to figure out a way to distinguish the intent of a link: is it a ‘real’ link, or a inter-page link?

The trivial solution, to just assume anything that doesn’t match a page is an external link won’t work with the red “bad link” feature.  We could check to see if is the link parses as a valid URL, perhaps.

**Comment by dtu-compute** [comment]
I see.

At some point they want to be able to rename the pages and have Danish versions as well, so it would be great, if we could begin to treat all pages the same when we encounter some that get special treatment.

Your solution sounds good.

If it is costly to check each external link, then perhaps we should have a "Check external links" button?

If external links are required to start with `http` the the red error bar would still work, right?

**Comment by iainbryson** [comment]
> On Feb 7, 2017, at 8:40 AM, dtu-compute <notifications@github.com> wrote:
> 
> I see.
> 
> At some point they want to be able to rename the pages and have Danish versions as well, so it would be great, if we could begin to treat all pages the same when we encounter some that get special treatment.
> 
> Your solution sounds good.
> 
> If it is costly to check each external link, then perhaps we should have a "Check external links" button?
> 
> If external links are required to start with http the the red error bar would still work, right?
> 
> —
> 

The ‘http’ part is pretty much what I’m suggesting: try to parse the link string as an URL.  So it won’t be costly — we’re not actually going to try and talk with the server — and anything which isn’t an valid URL must either be the name of a page or an error.  Sound reasonable?

**Comment by dtu-compute** [comment]
Perfect =)
