### ISSUE TITLE
Make site mobile-responsive

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#77]

**Comment by iainbryson** [comment]
Is this was the bug is about?

![image](https://cloud.githubusercontent.com/assets/1531103/25777896/cf8a205a-32a1-11e7-88b4-ce5b06d2ba46.png)

Basically, once the screen width goes below a certain threshold (IIRC, 768px), Bootstrap will show the mobile view.  The CSS for that is very much unfinished. 

I assume if you want to fix the logo, it would also make sense to fix all the other issues on this view.  Is that correct?

**Comment by dtu-compute** [comment]
Yes, let's take this one where there are no more >low tickets, as it could be hot fixed in.
