### ISSUE TITLE
Can't get Definition lists rendered

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-website#92]
In https://01005-staging.compute.dtu.dk/Semesteruge01?mode=edit I have

```
### Dagens Maple-pensum

D
:   alternativ til `diff` når der skal differentieres, fx partielt
diff med tilde
:   kan differentiere en vektor
vop
:   kan trække elementerne ud af en vektorer

```

but it is as if Markdown Extra isn't enabled.

**Comment by iainbryson** [comment]
I'm not admin on 01005, but why I try it locally, it seems to work as expected:

![image](https://cloud.githubusercontent.com/assets/1531103/26559005/952db602-4461-11e7-8fcb-12b17850fc05.png)


When you inspect the elements in 01005 in the editor, do you not see <dl>, <dd>, etc..?  Or is this a question of the styling of the definition list?

**Comment by dtu-compute** [comment]
The list is also corrupt on your screenshot. `D`, `diff med tilde`, `vop` should all be bold and left centered. 

Here is how it looks in stackedit.

![1](https://cloud.githubusercontent.com/assets/13518486/26559752/caee5b52-44b1-11e7-8dd4-75d790139e09.png)

**Comment by iainbryson** [comment]
I can get the rendering I think you’re looking for (“. D, diff med tilde,
vop should all be bold and left centered.”) by adding newlines:

https://00000-devel2.compute.dtu.dk/definition_list

https://github.com/jmcmanus/pagedown-extra also has an empty line
separating new definitions.

If I’m still not understanding correctly, can you put the examples up on
-devel2?  That way I can see both the edit and view, which I can’t for
courses on staging, since I’m not admin there.

**Comment by dtu-compute** [comment]
Ok, I see. I didn't expect there to be new lines between.

I'll put them up on devel2 in the future =) Your `iajbrys` user should be admin though on 01005 according to `/vol/config/cn-dumper.yaml`.
